server:
  port: 8080
  servlet:
    context-path: /clothing-store

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/clothing_store"
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true